const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),express=require('express');
const {PGlite}=require('@electric-sql/pglite');
const {installBtpOperations}=require('../btpOperations');
const {calculateQuote}=require('../btpMoney');
test('cent calculations and input precision',()=>{
 assert.deepEqual(calculateQuote([{quantity:100,basePriceUsd:1.3}],10,20),{subtotalUsd:130,commissionUsd:13,transportUsd:20,totalUsd:163});
 assert.equal(calculateQuote([{quantity:3,basePriceUsd:0.1}],10,0).totalUsd,0.33);
 assert.throws(()=>calculateQuote([{quantity:1,basePriceUsd:1.001}],0,0));
 assert.throws(()=>calculateQuote([{quantity:1,basePriceUsd:1}],100.01,0));
});
test('PostgreSQL engine: lifecycle, access control, stock, missions and settlements',{timeout:120000},async()=>{
 const pg=new PGlite();const schema=fs.readFileSync(path.join(__dirname,'../schema.sql'),'utf8').replace('CREATE EXTENSION IF NOT EXISTS pgcrypto;','');
 await pg.exec(schema);await pg.exec(schema);
 const query=async(sql,p=[])=>{const r=await pg.query(sql,p);return {...r,rowCount:r.rows.length||r.affectedRows||0};};
 const database={query,connect:async()=>({query,release(){}})},ids={};
 for(const role of ['admin','customer','other','staff','vendor','vendor2']){
  const c=(await query('INSERT INTO customer(full_name) VALUES($1) RETURNING id',[role])).rows[0].id;
  const r=['other'].includes(role)?'customer':role.startsWith('vendor')?'vendor':role;
  const u=(await query('INSERT INTO user_account(customer_id,email,password_hash,role) VALUES($1,$2,$3,$4) RETURNING id',[c,role+'@test.example','not-a-login-hash',r])).rows[0].id;
  ids[role]={userId:u,customerId:c,role:r};
  if(r==='vendor')ids[role].vendorId=(await query("INSERT INTO vendor(user_id,business_name,category) VALUES($1,$2,'partenaires') RETURNING id",[u,role])).rows[0].id;
 }
 await query("INSERT INTO product(id,name_fr,name_en,unit,price_usd,stock_qty) VALUES('CH-BLC-15','Bloc','Block','pcs',1.3,1000)");
 const app=express();app.use(express.json());installBtpOperations(app,{database,requireAuthentication:(req,res,next)=>{const a=ids[req.get('X-Test-Actor')];if(!a)return res.status(401).json({});req.auth=a;next();},requireRole:(...roles)=>(req,res,next)=>roles.includes(req.auth.role)?next():res.status(403).json({})});
 app.use((e,req,res,next)=>res.status(500).json({message:e.message}));
 const server=await new Promise(resolve=>{const s=app.listen(0,'127.0.0.1',()=>resolve(s));});const base=`http://127.0.0.1:${server.address().port}/api/btp`;
 const req=async(actor,url,method='GET',body)=>{const r=await fetch(base+url,{method,headers:{'Content-Type':'application/json','X-Test-Actor':actor},body:body===undefined?undefined:JSON.stringify(body)});return {status:r.status,body:await r.json()};};
 const check=async(actor,url,method,body,status)=>{const r=await req(actor,url,method,body);assert.equal(r.status,status,JSON.stringify(r));return r.body;};
 try{
  await check('','/quotes','GET',undefined,401);
  const q=(await check('customer','/quotes','POST',{customerId:ids.other.customerId,request:'100 blocs pour mon chantier',destination:'Kolwezi centre'},201)).quote;
  assert.equal(q.customer_id,ids.customer.customerId);const id=q.id;
  await check('other','/quotes/'+id,'GET',undefined,404);await check('vendor','/quotes','GET',undefined,403);
  const v={expectedRevision:0,lines:[{description:'Bloc 15',unit:'pcs',productId:'CH-BLC-15',quantity:100,basePriceUsd:1.3,vendorId:ids.vendor.vendorId}],commissionPercent:10,transportUsd:20,terms:'Transport et déchargement confirmés. Paiement Airtel Money.',validUntil:new Date(Date.now()+86400000).toISOString(),publish:true,availabilityConfirmed:true};
  await check('customer',`/quotes/${id}/revisions`,'POST',v,403);
  await check('admin',`/quotes/${id}/revisions`,'POST',{...v,lines:[{...v.lines[0],quantity:99}]},400);
  await check('admin',`/quotes/${id}/revisions`,'POST',v,201);await check('admin',`/quotes/${id}/revisions`,'POST',v,409);
  const view=await check('customer','/quotes/'+id,'GET',undefined,200);assert.equal(view.revisions[0].lines[0].basePriceUsd,undefined);assert.equal(Number(view.revisions[0].total_usd),163);
  await check('customer',`/quotes/${id}/decision`,'POST',{expectedRevision:2,decision:'accepted'},409);
  await check('other',`/quotes/${id}/decision`,'POST',{expectedRevision:1,decision:'accepted'},404);
  await check('customer',`/quotes/${id}/decision`,'POST',{expectedRevision:1,decision:'accepted'},200);
  await check('admin',`/quotes/${id}/revisions`,'POST',{...v,expectedRevision:1},409);
  const o=(await check('admin',`/quotes/${id}/order`,'POST',{paymentProvider:'airtel_money'},200)).order;assert.equal(Number(o.total_amount),163);
  const again=(await check('admin',`/quotes/${id}/order`,'POST',{paymentProvider:'airtel_money'},200)).order;assert.equal(again.id,o.id);
  assert.equal(Number((await query("SELECT stock_qty FROM product WHERE id='CH-BLC-15'")).rows[0].stock_qty),900);
  const mb={orderId:o.id,carrierVendorId:ids.vendor.vendorId,driverUserId:ids.staff.userId,vehicle:'Camion ABC 001',origin:'Dépôt Kolwezi',destination:'Kolwezi centre',loadDescription:'100 blocs',plannedAt:new Date(Date.now()+3600000).toISOString()};
  await check('admin','/missions','POST',mb,409);await query("UPDATE orders SET status='confirmed' WHERE id=$1",[o.id]);
  const m=(await check('admin','/missions','POST',mb,201)).mission;
  assert.equal((await req('other','/missions')).body.missions.length,0);
  await check('vendor2',`/missions/${m.id}/status`,'PATCH',{status:'in_transit'},404);
  await check('staff',`/missions/${m.id}/status`,'PATCH',{status:'delivered',proof:'BL001'},409);
  await check('staff',`/missions/${m.id}/status`,'PATCH',{status:'in_transit'},200);
  await check('staff',`/missions/${m.id}/status`,'PATCH',{status:'delivered'},400);
  await check('staff',`/missions/${m.id}/status`,'PATCH',{status:'delivered',proof:'Bon signé BL001'},200);
  await check('staff',`/missions/${m.id}/status`,'PATCH',{status:'completed',proof:'Client BL001'},403);
  await check('admin',`/missions/${m.id}/status`,'PATCH',{status:'completed',proof:'Client BL001'},200);
  const sb={orderId:o.id,vendorId:ids.vendor.vendorId,purpose:'Fourniture blocs',amountUsd:130};
  await check('admin','/settlements','POST',sb,409);await query("UPDATE orders SET status='completed' WHERE id=$1",[o.id]);
  const s=(await check('admin','/settlements','POST',sb,201)).settlement;
  await check('admin','/settlements','POST',sb,409);
  await check('admin','/settlements','POST',{...sb,purpose:'Transport',amountUsd:40},409);
  assert.equal((await req('vendor2','/settlements')).body.settlements.length,0);
  await check('vendor',`/settlements/${s.id}/status`,'PATCH',{status:'paid',paymentReference:'TX-001'},403);
  await check('admin',`/settlements/${s.id}/status`,'PATCH',{status:'paid',paymentReference:'TX-001'},409);
  await query("UPDATE payment SET status='paid' WHERE order_id=$1",[o.id]);
  await check('admin',`/settlements/${s.id}/status`,'PATCH',{status:'paid',paymentReference:'TX-001'},200);
  await check('admin',`/settlements/${s.id}/status`,'PATCH',{status:'paid',paymentReference:'TX-001'},200);
  await check('admin',`/settlements/${s.id}/status`,'PATCH',{status:'cancelled'},409);
  await check('customer',`/events/quote/${id}`,'GET',undefined,403);
  assert.equal((await req('admin',`/events/quote/${id}`)).body.events.length,4);
  const draft=(await check('customer','/quotes','POST',{request:'Prestation de plomberie',destination:'Kolwezi centre'},201)).quote;
  await check('admin',`/quotes/${draft.id}/revisions`,'POST',{...v,lines:[{description:'Intervention',unit:'service',quantity:1,basePriceUsd:50}],publish:false},201);
  assert.equal((await req('customer',`/quotes/${draft.id}`)).body.revisions.length,0);
  await check('admin',`/quotes/${draft.id}/cancel`,'POST',{},200);
  await check('customer',`/quotes/${draft.id}/decision`,'POST',{expectedRevision:1,decision:'accepted'},409);
  const shortage=(await check('customer','/quotes','POST',{request:'Mille blocs supplémentaires',destination:'Kolwezi centre'},201)).quote;
  await check('admin',`/quotes/${shortage.id}/revisions`,'POST',{...v,lines:[{...v.lines[0],quantity:1000}]},201);
  await check('customer',`/quotes/${shortage.id}/decision`,'POST',{expectedRevision:1,decision:'accepted'},200);
  await check('admin',`/quotes/${shortage.id}/order`,'POST',{paymentProvider:'airtel_money'},409);
  assert.equal(Number((await query("SELECT stock_qty FROM product WHERE id='CH-BLC-15'")).rows[0].stock_qty),900);
  assert.equal(Number((await query('SELECT COUNT(*) AS n FROM orders')).rows[0].n),1);
  const second=(await check('admin','/settlements','POST',{...sb,purpose:'Transport',amountUsd:20},201)).settlement;
  await check('admin',`/settlements/${second.id}/status`,'PATCH',{status:'paid',paymentReference:'TX-001'},409);
  assert.equal((await query('SELECT status FROM btp_settlement WHERE id=$1',[second.id])).rows[0].status,'due');
  const expired=(await check('customer','/quotes','POST',{request:'Autre devis',destination:'Kolwezi centre'},201)).quote;
  await check('admin',`/quotes/${expired.id}/revisions`,'POST',v,201);
  await query("UPDATE btp_quote_revision SET valid_until=now()-interval '1 day' WHERE quote_id=$1",[expired.id]);
  await check('customer',`/quotes/${expired.id}/decision`,'POST',{expectedRevision:1,decision:'accepted'},409);
 }finally{await new Promise(resolve=>server.close(resolve));await pg.close();}
});
