'use strict';

// Catalogue de référence. Les prix à 0 signifient « sur devis » et doivent être
// validés par un administrateur ou un fournisseur avant publication commerciale.
const CONSTRUCTION_CATALOG = [
  {
    "id": "PRD-0001",
    "name_fr": "Sable de rivière",
    "name_en": "River sand",
    "unit": "m³",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "produits",
    "stock": 0,
    "catalog_group": "aggregats"
  },
  {
    "id": "PRD-0002",
    "name_fr": "Sable lavé",
    "name_en": "Washed sand",
    "unit": "m³",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "produits",
    "stock": 0,
    "catalog_group": "aggregats"
  },
  {
    "id": "PRD-0003",
    "name_fr": "Sable jaune",
    "name_en": "Yellow sand",
    "unit": "m³",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "produits",
    "stock": 0,
    "catalog_group": "aggregats"
  },
  {
    "id": "PRD-0004",
    "name_fr": "Sable de remblai",
    "name_en": "Backfill sand",
    "unit": "m³",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "produits",
    "stock": 0,
    "catalog_group": "aggregats"
  },
  {
    "id": "PRD-0005",
    "name_fr": "Sable concassé 0/5",
    "name_en": "Crushed sand 0/5",
    "unit": "m³",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "produits",
    "stock": 0,
    "catalog_group": "aggregats"
  },
  {
    "id": "PRD-0006",
    "name_fr": "Poussière de carrière",
    "name_en": "Quarry dust",
    "unit": "m³",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "produits",
    "stock": 0,
    "catalog_group": "aggregats"
  },
  {
    "id": "PRD-0007",
    "name_fr": "Gravier 5/15",
    "name_en": "Gravel 5/15",
    "unit": "m³",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "produits",
    "stock": 0,
    "catalog_group": "aggregats"
  },
  {
    "id": "PRD-0008",
    "name_fr": "Gravier 8/15",
    "name_en": "Gravel 8/15",
    "unit": "m³",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "produits",
    "stock": 0,
    "catalog_group": "aggregats"
  },
  {
    "id": "PRD-0009",
    "name_fr": "Gravier 15/25",
    "name_en": "Gravel 15/25",
    "unit": "m³",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "produits",
    "stock": 0,
    "catalog_group": "aggregats"
  },
  {
    "id": "PRD-0010",
    "name_fr": "Gravier 20/40",
    "name_en": "Gravel 20/40",
    "unit": "m³",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "produits",
    "stock": 0,
    "catalog_group": "aggregats"
  },
  {
    "id": "PRD-0011",
    "name_fr": "Tout-venant",
    "name_en": "Crusher run",
    "unit": "m³",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "produits",
    "stock": 0,
    "catalog_group": "aggregats"
  },
  {
    "id": "PRD-0012",
    "name_fr": "Moellons",
    "name_en": "Rubble stones",
    "unit": "m³",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "produits",
    "stock": 0,
    "catalog_group": "aggregats"
  },
  {
    "id": "PRD-0013",
    "name_fr": "Pierres de fondation",
    "name_en": "Foundation stones",
    "unit": "m³",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "produits",
    "stock": 0,
    "catalog_group": "aggregats"
  },
  {
    "id": "PRD-0014",
    "name_fr": "Pierres décoratives",
    "name_en": "Decorative stones",
    "unit": "m²",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "produits",
    "stock": 0,
    "catalog_group": "aggregats"
  },
  {
    "id": "PRD-0015",
    "name_fr": "Latérite",
    "name_en": "Laterite",
    "unit": "m³",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "produits",
    "stock": 0,
    "catalog_group": "aggregats"
  },
  {
    "id": "PRD-0016",
    "name_fr": "Terre de remblai",
    "name_en": "Backfill soil",
    "unit": "m³",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "produits",
    "stock": 0,
    "catalog_group": "aggregats"
  },
  {
    "id": "PRD-0017",
    "name_fr": "Ballast",
    "name_en": "Ballast",
    "unit": "tonne",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "produits",
    "stock": 0,
    "catalog_group": "aggregats"
  },
  {
    "id": "PRD-0018",
    "name_fr": "Chaux",
    "name_en": "Lime",
    "unit": "sac",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "produits",
    "stock": 0,
    "catalog_group": "aggregats"
  },
  {
    "id": "PRD-0019",
    "name_fr": "Ciment gris 50 kg",
    "name_en": "Grey cement 50 kg",
    "unit": "sac",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "produits",
    "stock": 0,
    "catalog_group": "aggregats"
  },
  {
    "id": "PRD-0020",
    "name_fr": "Ciment blanc",
    "name_en": "White cement",
    "unit": "sac",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "produits",
    "stock": 0,
    "catalog_group": "aggregats"
  },
  {
    "id": "PRD-0021",
    "name_fr": "Ciment-colle",
    "name_en": "Tile adhesive cement",
    "unit": "sac",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "produits",
    "stock": 0,
    "catalog_group": "aggregats"
  },
  {
    "id": "PRD-0022",
    "name_fr": "Béton prêt à l’emploi",
    "name_en": "Ready-mix concrete",
    "unit": "m³",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "produits",
    "stock": 0,
    "catalog_group": "aggregats"
  },
  {
    "id": "PRD-0023",
    "name_fr": "Mortier prêt à l’emploi",
    "name_en": "Ready-mix mortar",
    "unit": "sac",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "produits",
    "stock": 0,
    "catalog_group": "aggregats"
  },
  {
    "id": "PRD-0024",
    "name_fr": "Adjuvant pour béton",
    "name_en": "Concrete admixture",
    "unit": "litre",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "produits",
    "stock": 0,
    "catalog_group": "aggregats"
  },
  {
    "id": "PRD-0025",
    "name_fr": "Briques cuites",
    "name_en": "Fired bricks",
    "unit": "unité",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "produits",
    "stock": 0,
    "catalog_group": "blocs_paves"
  },
  {
    "id": "PRD-0026",
    "name_fr": "Briques stabilisées",
    "name_en": "Stabilized bricks",
    "unit": "unité",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "produits",
    "stock": 0,
    "catalog_group": "blocs_paves"
  },
  {
    "id": "PRD-0027",
    "name_fr": "Blocs creux en ciment",
    "name_en": "Hollow concrete blocks",
    "unit": "unité",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "produits",
    "stock": 0,
    "catalog_group": "blocs_paves"
  },
  {
    "id": "PRD-0028",
    "name_fr": "Blocs pleins",
    "name_en": "Solid concrete blocks",
    "unit": "unité",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "produits",
    "stock": 0,
    "catalog_group": "blocs_paves"
  },
  {
    "id": "PRD-0029",
    "name_fr": "Blocs de fondation",
    "name_en": "Foundation blocks",
    "unit": "unité",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "produits",
    "stock": 0,
    "catalog_group": "blocs_paves"
  },
  {
    "id": "PRD-0030",
    "name_fr": "Blocs décoratifs",
    "name_en": "Decorative blocks",
    "unit": "unité",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "produits",
    "stock": 0,
    "catalog_group": "blocs_paves"
  },
  {
    "id": "PRD-0031",
    "name_fr": "Blocs cellulaires",
    "name_en": "Aerated concrete blocks",
    "unit": "unité",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "produits",
    "stock": 0,
    "catalog_group": "blocs_paves"
  },
  {
    "id": "PRD-0032",
    "name_fr": "Hourdis",
    "name_en": "Floor blocks",
    "unit": "unité",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "produits",
    "stock": 0,
    "catalog_group": "blocs_paves"
  },
  {
    "id": "PRD-0033",
    "name_fr": "Pavés autobloquants",
    "name_en": "Interlocking pavers",
    "unit": "m²",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "produits",
    "stock": 0,
    "catalog_group": "blocs_paves"
  },
  {
    "id": "PRD-0034",
    "name_fr": "Pavés décoratifs",
    "name_en": "Decorative pavers",
    "unit": "m²",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "produits",
    "stock": 0,
    "catalog_group": "blocs_paves"
  },
  {
    "id": "PRD-0035",
    "name_fr": "Bordures de route",
    "name_en": "Road curbs",
    "unit": "unité",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "produits",
    "stock": 0,
    "catalog_group": "blocs_paves"
  },
  {
    "id": "PRD-0036",
    "name_fr": "Caniveaux préfabriqués",
    "name_en": "Precast drains",
    "unit": "unité",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "produits",
    "stock": 0,
    "catalog_group": "blocs_paves"
  },
  {
    "id": "PRD-0037",
    "name_fr": "Dalles préfabriquées",
    "name_en": "Precast slabs",
    "unit": "unité",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "produits",
    "stock": 0,
    "catalog_group": "blocs_paves"
  },
  {
    "id": "PRD-0038",
    "name_fr": "Claustras",
    "name_en": "Screen blocks",
    "unit": "unité",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "produits",
    "stock": 0,
    "catalog_group": "blocs_paves"
  },
  {
    "id": "PRD-0039",
    "name_fr": "Linteaux préfabriqués",
    "name_en": "Precast lintels",
    "unit": "unité",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "produits",
    "stock": 0,
    "catalog_group": "blocs_paves"
  },
  {
    "id": "PRD-0040",
    "name_fr": "Poteaux en béton",
    "name_en": "Concrete posts",
    "unit": "unité",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "produits",
    "stock": 0,
    "catalog_group": "blocs_paves"
  },
  {
    "id": "PRD-0041",
    "name_fr": "Buses en béton",
    "name_en": "Concrete pipes",
    "unit": "unité",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "produits",
    "stock": 0,
    "catalog_group": "blocs_paves"
  },
  {
    "id": "PRD-0042",
    "name_fr": "Fosses septiques préfabriquées",
    "name_en": "Precast septic tanks",
    "unit": "unité",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "produits",
    "stock": 0,
    "catalog_group": "blocs_paves"
  },
  {
    "id": "PRD-0043",
    "name_fr": "Regards en béton",
    "name_en": "Concrete manholes",
    "unit": "unité",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "produits",
    "stock": 0,
    "catalog_group": "blocs_paves"
  },
  {
    "id": "PRD-0044",
    "name_fr": "Barres à béton",
    "name_en": "Reinforcement bars",
    "unit": "barre",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "produits",
    "stock": 0,
    "catalog_group": "acier_metaux"
  },
  {
    "id": "PRD-0045",
    "name_fr": "Treillis soudés",
    "name_en": "Welded mesh",
    "unit": "panneau",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "produits",
    "stock": 0,
    "catalog_group": "acier_metaux"
  },
  {
    "id": "PRD-0046",
    "name_fr": "Fils d’attache",
    "name_en": "Binding wire",
    "unit": "rouleau",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "produits",
    "stock": 0,
    "catalog_group": "acier_metaux"
  },
  {
    "id": "PRD-0047",
    "name_fr": "Profilés UPN",
    "name_en": "UPN steel sections",
    "unit": "barre",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "produits",
    "stock": 0,
    "catalog_group": "acier_metaux"
  },
  {
    "id": "PRD-0048",
    "name_fr": "Profilés IPN",
    "name_en": "IPN steel sections",
    "unit": "barre",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "produits",
    "stock": 0,
    "catalog_group": "acier_metaux"
  },
  {
    "id": "PRD-0049",
    "name_fr": "Profilés IPE",
    "name_en": "IPE steel sections",
    "unit": "barre",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "produits",
    "stock": 0,
    "catalog_group": "acier_metaux"
  },
  {
    "id": "PRD-0050",
    "name_fr": "Profilés HEA",
    "name_en": "HEA steel sections",
    "unit": "barre",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "produits",
    "stock": 0,
    "catalog_group": "acier_metaux"
  },
  {
    "id": "PRD-0051",
    "name_fr": "Cornières",
    "name_en": "Steel angles",
    "unit": "barre",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "produits",
    "stock": 0,
    "catalog_group": "acier_metaux"
  },
  {
    "id": "PRD-0052",
    "name_fr": "Tubes carrés",
    "name_en": "Square steel tubes",
    "unit": "barre",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "produits",
    "stock": 0,
    "catalog_group": "acier_metaux"
  },
  {
    "id": "PRD-0053",
    "name_fr": "Tubes rectangulaires",
    "name_en": "Rectangular steel tubes",
    "unit": "barre",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "produits",
    "stock": 0,
    "catalog_group": "acier_metaux"
  },
  {
    "id": "PRD-0054",
    "name_fr": "Tubes ronds",
    "name_en": "Round steel tubes",
    "unit": "barre",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "produits",
    "stock": 0,
    "catalog_group": "acier_metaux"
  },
  {
    "id": "PRD-0055",
    "name_fr": "Tôles noires",
    "name_en": "Black steel sheets",
    "unit": "feuille",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "produits",
    "stock": 0,
    "catalog_group": "acier_metaux"
  },
  {
    "id": "PRD-0056",
    "name_fr": "Tôles galvanisées",
    "name_en": "Galvanized sheets",
    "unit": "feuille",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "produits",
    "stock": 0,
    "catalog_group": "acier_metaux"
  },
  {
    "id": "PRD-0057",
    "name_fr": "Tôles striées",
    "name_en": "Checker plates",
    "unit": "feuille",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "produits",
    "stock": 0,
    "catalog_group": "acier_metaux"
  },
  {
    "id": "PRD-0058",
    "name_fr": "Tôles perforées",
    "name_en": "Perforated sheets",
    "unit": "feuille",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "produits",
    "stock": 0,
    "catalog_group": "acier_metaux"
  },
  {
    "id": "PRD-0059",
    "name_fr": "Grillages",
    "name_en": "Wire mesh",
    "unit": "rouleau",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "produits",
    "stock": 0,
    "catalog_group": "acier_metaux"
  },
  {
    "id": "PRD-0060",
    "name_fr": "Fils barbelés",
    "name_en": "Barbed wire",
    "unit": "rouleau",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "produits",
    "stock": 0,
    "catalog_group": "acier_metaux"
  },
  {
    "id": "PRD-0061",
    "name_fr": "Gabions métalliques",
    "name_en": "Metal gabions",
    "unit": "unité",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "produits",
    "stock": 0,
    "catalog_group": "acier_metaux"
  },
  {
    "id": "PRD-0062",
    "name_fr": "Clous",
    "name_en": "Nails",
    "unit": "kg",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "produits",
    "stock": 0,
    "catalog_group": "acier_metaux"
  },
  {
    "id": "PRD-0063",
    "name_fr": "Vis",
    "name_en": "Screws",
    "unit": "boîte",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "produits",
    "stock": 0,
    "catalog_group": "acier_metaux"
  },
  {
    "id": "PRD-0064",
    "name_fr": "Boulons et écrous",
    "name_en": "Bolts and nuts",
    "unit": "boîte",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "produits",
    "stock": 0,
    "catalog_group": "acier_metaux"
  },
  {
    "id": "PRD-0065",
    "name_fr": "Électrodes de soudure",
    "name_en": "Welding electrodes",
    "unit": "boîte",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "produits",
    "stock": 0,
    "catalog_group": "acier_metaux"
  },
  {
    "id": "PRD-0066",
    "name_fr": "Disques de coupe",
    "name_en": "Cutting discs",
    "unit": "unité",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "produits",
    "stock": 0,
    "catalog_group": "acier_metaux"
  },
  {
    "id": "PRD-0067",
    "name_fr": "Portes métalliques",
    "name_en": "Metal doors",
    "unit": "unité",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "produits",
    "stock": 0,
    "catalog_group": "acier_metaux"
  },
  {
    "id": "PRD-0068",
    "name_fr": "Fenêtres métalliques",
    "name_en": "Metal windows",
    "unit": "unité",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "produits",
    "stock": 0,
    "catalog_group": "acier_metaux"
  },
  {
    "id": "PRD-0069",
    "name_fr": "Grilles métalliques",
    "name_en": "Metal security grilles",
    "unit": "unité",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "produits",
    "stock": 0,
    "catalog_group": "acier_metaux"
  },
  {
    "id": "PRD-0070",
    "name_fr": "Portails métalliques",
    "name_en": "Metal gates",
    "unit": "unité",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "produits",
    "stock": 0,
    "catalog_group": "acier_metaux"
  },
  {
    "id": "PRD-0071",
    "name_fr": "Charpentes métalliques",
    "name_en": "Steel roof frames",
    "unit": "projet",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "produits",
    "stock": 0,
    "catalog_group": "acier_metaux"
  },
  {
    "id": "PRD-0072",
    "name_fr": "Citernes métalliques",
    "name_en": "Metal tanks",
    "unit": "unité",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "produits",
    "stock": 0,
    "catalog_group": "acier_metaux"
  },
  {
    "id": "PRD-0073",
    "name_fr": "Planches",
    "name_en": "Boards",
    "unit": "pièce",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "produits",
    "stock": 0,
    "catalog_group": "bois_menuiserie"
  },
  {
    "id": "PRD-0074",
    "name_fr": "Madriers",
    "name_en": "Timber beams",
    "unit": "pièce",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "produits",
    "stock": 0,
    "catalog_group": "bois_menuiserie"
  },
  {
    "id": "PRD-0075",
    "name_fr": "Chevrons",
    "name_en": "Rafters",
    "unit": "pièce",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "produits",
    "stock": 0,
    "catalog_group": "bois_menuiserie"
  },
  {
    "id": "PRD-0076",
    "name_fr": "Liteaux",
    "name_en": "Battens",
    "unit": "pièce",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "produits",
    "stock": 0,
    "catalog_group": "bois_menuiserie"
  },
  {
    "id": "PRD-0077",
    "name_fr": "Bois de coffrage",
    "name_en": "Formwork timber",
    "unit": "pièce",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "produits",
    "stock": 0,
    "catalog_group": "bois_menuiserie"
  },
  {
    "id": "PRD-0078",
    "name_fr": "Contreplaqué ordinaire",
    "name_en": "Standard plywood",
    "unit": "feuille",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "produits",
    "stock": 0,
    "catalog_group": "bois_menuiserie"
  },
  {
    "id": "PRD-0079",
    "name_fr": "Contreplaqué marin",
    "name_en": "Marine plywood",
    "unit": "feuille",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "produits",
    "stock": 0,
    "catalog_group": "bois_menuiserie"
  },
  {
    "id": "PRD-0080",
    "name_fr": "Panneaux MDF",
    "name_en": "MDF panels",
    "unit": "feuille",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "produits",
    "stock": 0,
    "catalog_group": "bois_menuiserie"
  },
  {
    "id": "PRD-0081",
    "name_fr": "Panneaux mélaminés",
    "name_en": "Melamine panels",
    "unit": "feuille",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "produits",
    "stock": 0,
    "catalog_group": "bois_menuiserie"
  },
  {
    "id": "PRD-0082",
    "name_fr": "Panneaux agglomérés",
    "name_en": "Particle boards",
    "unit": "feuille",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "produits",
    "stock": 0,
    "catalog_group": "bois_menuiserie"
  },
  {
    "id": "PRD-0083",
    "name_fr": "Lambris",
    "name_en": "Wood panelling",
    "unit": "m²",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "produits",
    "stock": 0,
    "catalog_group": "bois_menuiserie"
  },
  {
    "id": "PRD-0084",
    "name_fr": "Parquet massif",
    "name_en": "Solid wood flooring",
    "unit": "m²",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "produits",
    "stock": 0,
    "catalog_group": "bois_menuiserie"
  },
  {
    "id": "PRD-0085",
    "name_fr": "Parquet stratifié",
    "name_en": "Laminate flooring",
    "unit": "m²",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "produits",
    "stock": 0,
    "catalog_group": "bois_menuiserie"
  },
  {
    "id": "PRD-0086",
    "name_fr": "Portes en bois",
    "name_en": "Wooden doors",
    "unit": "unité",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "produits",
    "stock": 0,
    "catalog_group": "bois_menuiserie"
  },
  {
    "id": "PRD-0087",
    "name_fr": "Fenêtres en bois",
    "name_en": "Wooden windows",
    "unit": "unité",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "produits",
    "stock": 0,
    "catalog_group": "bois_menuiserie"
  },
  {
    "id": "PRD-0088",
    "name_fr": "Placards et dressings",
    "name_en": "Wardrobes and closets",
    "unit": "projet",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "produits",
    "stock": 0,
    "catalog_group": "bois_menuiserie"
  },
  {
    "id": "PRD-0089",
    "name_fr": "Meubles de cuisine",
    "name_en": "Kitchen cabinets",
    "unit": "projet",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "produits",
    "stock": 0,
    "catalog_group": "bois_menuiserie"
  },
  {
    "id": "PRD-0090",
    "name_fr": "Quincaillerie de menuiserie",
    "name_en": "Carpentry hardware",
    "unit": "lot",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "produits",
    "stock": 0,
    "catalog_group": "bois_menuiserie"
  },
  {
    "id": "PRD-0091",
    "name_fr": "Colle à bois",
    "name_en": "Wood glue",
    "unit": "unité",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "produits",
    "stock": 0,
    "catalog_group": "bois_menuiserie"
  },
  {
    "id": "PRD-0092",
    "name_fr": "Vernis et lasures",
    "name_en": "Varnish and wood stain",
    "unit": "litre",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "produits",
    "stock": 0,
    "catalog_group": "bois_menuiserie"
  },
  {
    "id": "PRD-0093",
    "name_fr": "Tôles ondulées",
    "name_en": "Corrugated roofing sheets",
    "unit": "feuille",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "produits",
    "stock": 0,
    "catalog_group": "toiture_etancheite"
  },
  {
    "id": "PRD-0094",
    "name_fr": "Tôles prélaquées",
    "name_en": "Pre-painted roofing sheets",
    "unit": "feuille",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "produits",
    "stock": 0,
    "catalog_group": "toiture_etancheite"
  },
  {
    "id": "PRD-0095",
    "name_fr": "Tuiles métalliques",
    "name_en": "Metal roof tiles",
    "unit": "m²",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "produits",
    "stock": 0,
    "catalog_group": "toiture_etancheite"
  },
  {
    "id": "PRD-0096",
    "name_fr": "Tuiles en béton",
    "name_en": "Concrete roof tiles",
    "unit": "m²",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "produits",
    "stock": 0,
    "catalog_group": "toiture_etancheite"
  },
  {
    "id": "PRD-0097",
    "name_fr": "Tuiles en terre cuite",
    "name_en": "Clay roof tiles",
    "unit": "m²",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "produits",
    "stock": 0,
    "catalog_group": "toiture_etancheite"
  },
  {
    "id": "PRD-0098",
    "name_fr": "Tôles transparentes",
    "name_en": "Transparent roofing sheets",
    "unit": "feuille",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "produits",
    "stock": 0,
    "catalog_group": "toiture_etancheite"
  },
  {
    "id": "PRD-0099",
    "name_fr": "Faîtières",
    "name_en": "Ridge caps",
    "unit": "pièce",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "produits",
    "stock": 0,
    "catalog_group": "toiture_etancheite"
  },
  {
    "id": "PRD-0100",
    "name_fr": "Noues et solins",
    "name_en": "Roof valleys and flashings",
    "unit": "pièce",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "produits",
    "stock": 0,
    "catalog_group": "toiture_etancheite"
  },
  {
    "id": "PRD-0101",
    "name_fr": "Gouttières",
    "name_en": "Gutters",
    "unit": "mètre",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "produits",
    "stock": 0,
    "catalog_group": "toiture_etancheite"
  },
  {
    "id": "PRD-0102",
    "name_fr": "Descentes pluviales",
    "name_en": "Downpipes",
    "unit": "mètre",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "produits",
    "stock": 0,
    "catalog_group": "toiture_etancheite"
  },
  {
    "id": "PRD-0103",
    "name_fr": "Membranes bitumineuses",
    "name_en": "Bituminous membranes",
    "unit": "rouleau",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "produits",
    "stock": 0,
    "catalog_group": "toiture_etancheite"
  },
  {
    "id": "PRD-0104",
    "name_fr": "Produits d’étanchéité",
    "name_en": "Waterproofing products",
    "unit": "unité",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "produits",
    "stock": 0,
    "catalog_group": "toiture_etancheite"
  },
  {
    "id": "PRD-0105",
    "name_fr": "Mastics et silicones",
    "name_en": "Sealants and silicone",
    "unit": "cartouche",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "produits",
    "stock": 0,
    "catalog_group": "toiture_etancheite"
  },
  {
    "id": "PRD-0106",
    "name_fr": "Plaques de plâtre",
    "name_en": "Plasterboards",
    "unit": "feuille",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "produits",
    "stock": 0,
    "catalog_group": "toiture_etancheite"
  },
  {
    "id": "PRD-0107",
    "name_fr": "Plafonds PVC",
    "name_en": "PVC ceilings",
    "unit": "m²",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "produits",
    "stock": 0,
    "catalog_group": "toiture_etancheite"
  },
  {
    "id": "PRD-0108",
    "name_fr": "Profilés de plafond",
    "name_en": "Ceiling profiles",
    "unit": "barre",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "produits",
    "stock": 0,
    "catalog_group": "toiture_etancheite"
  },
  {
    "id": "PRD-0109",
    "name_fr": "Corniches et rosaces",
    "name_en": "Cornices and ceiling roses",
    "unit": "unité",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "produits",
    "stock": 0,
    "catalog_group": "toiture_etancheite"
  },
  {
    "id": "PRD-0110",
    "name_fr": "Isolants thermiques",
    "name_en": "Thermal insulation",
    "unit": "m²",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "produits",
    "stock": 0,
    "catalog_group": "toiture_etancheite"
  },
  {
    "id": "PRD-0111",
    "name_fr": "Isolants acoustiques",
    "name_en": "Acoustic insulation",
    "unit": "m²",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "produits",
    "stock": 0,
    "catalog_group": "toiture_etancheite"
  },
  {
    "id": "PRD-0112",
    "name_fr": "Carreaux de sol",
    "name_en": "Floor tiles",
    "unit": "m²",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "produits",
    "stock": 0,
    "catalog_group": "revetements_finitions"
  },
  {
    "id": "PRD-0113",
    "name_fr": "Carreaux muraux",
    "name_en": "Wall tiles",
    "unit": "m²",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "produits",
    "stock": 0,
    "catalog_group": "revetements_finitions"
  },
  {
    "id": "PRD-0114",
    "name_fr": "Grès cérame",
    "name_en": "Porcelain stoneware",
    "unit": "m²",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "produits",
    "stock": 0,
    "catalog_group": "revetements_finitions"
  },
  {
    "id": "PRD-0115",
    "name_fr": "Faïence",
    "name_en": "Ceramic wall tiles",
    "unit": "m²",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "produits",
    "stock": 0,
    "catalog_group": "revetements_finitions"
  },
  {
    "id": "PRD-0116",
    "name_fr": "Marbre",
    "name_en": "Marble",
    "unit": "m²",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "produits",
    "stock": 0,
    "catalog_group": "revetements_finitions"
  },
  {
    "id": "PRD-0117",
    "name_fr": "Granit",
    "name_en": "Granite",
    "unit": "m²",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "produits",
    "stock": 0,
    "catalog_group": "revetements_finitions"
  },
  {
    "id": "PRD-0118",
    "name_fr": "Quartz",
    "name_en": "Quartz slabs",
    "unit": "m²",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "produits",
    "stock": 0,
    "catalog_group": "revetements_finitions"
  },
  {
    "id": "PRD-0119",
    "name_fr": "Mosaïque",
    "name_en": "Mosaic tiles",
    "unit": "m²",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "produits",
    "stock": 0,
    "catalog_group": "revetements_finitions"
  },
  {
    "id": "PRD-0120",
    "name_fr": "Plinthes",
    "name_en": "Skirting boards",
    "unit": "mètre",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "produits",
    "stock": 0,
    "catalog_group": "revetements_finitions"
  },
  {
    "id": "PRD-0121",
    "name_fr": "Revêtement vinyle",
    "name_en": "Vinyl flooring",
    "unit": "m²",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "produits",
    "stock": 0,
    "catalog_group": "revetements_finitions"
  },
  {
    "id": "PRD-0122",
    "name_fr": "Moquette",
    "name_en": "Carpet",
    "unit": "m²",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "produits",
    "stock": 0,
    "catalog_group": "revetements_finitions"
  },
  {
    "id": "PRD-0123",
    "name_fr": "Colle à carreaux",
    "name_en": "Tile adhesive",
    "unit": "sac",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "produits",
    "stock": 0,
    "catalog_group": "revetements_finitions"
  },
  {
    "id": "PRD-0124",
    "name_fr": "Croisillons et cales",
    "name_en": "Tile spacers and wedges",
    "unit": "paquet",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "produits",
    "stock": 0,
    "catalog_group": "revetements_finitions"
  },
  {
    "id": "PRD-0125",
    "name_fr": "Systèmes de nivellement",
    "name_en": "Tile levelling systems",
    "unit": "kit",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "produits",
    "stock": 0,
    "catalog_group": "revetements_finitions"
  },
  {
    "id": "PRD-0126",
    "name_fr": "Joints de carrelage",
    "name_en": "Tile grout",
    "unit": "sac",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "produits",
    "stock": 0,
    "catalog_group": "revetements_finitions"
  },
  {
    "id": "PRD-0127",
    "name_fr": "Enduits intérieurs",
    "name_en": "Interior render",
    "unit": "sac",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "produits",
    "stock": 0,
    "catalog_group": "revetements_finitions"
  },
  {
    "id": "PRD-0128",
    "name_fr": "Enduits extérieurs",
    "name_en": "Exterior render",
    "unit": "sac",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "produits",
    "stock": 0,
    "catalog_group": "revetements_finitions"
  },
  {
    "id": "PRD-0129",
    "name_fr": "Crépi",
    "name_en": "Textured render",
    "unit": "sac",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "produits",
    "stock": 0,
    "catalog_group": "revetements_finitions"
  },
  {
    "id": "PRD-0130",
    "name_fr": "Papier peint",
    "name_en": "Wallpaper",
    "unit": "rouleau",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "produits",
    "stock": 0,
    "catalog_group": "revetements_finitions"
  },
  {
    "id": "PRD-0131",
    "name_fr": "Panneaux muraux décoratifs",
    "name_en": "Decorative wall panels",
    "unit": "m²",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "produits",
    "stock": 0,
    "catalog_group": "revetements_finitions"
  },
  {
    "id": "PRD-0132",
    "name_fr": "Bardage extérieur",
    "name_en": "Exterior cladding",
    "unit": "m²",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "produits",
    "stock": 0,
    "catalog_group": "revetements_finitions"
  },
  {
    "id": "PRD-0133",
    "name_fr": "Peinture à eau",
    "name_en": "Water-based paint",
    "unit": "seau",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "produits",
    "stock": 0,
    "catalog_group": "revetements_finitions"
  },
  {
    "id": "PRD-0134",
    "name_fr": "Peinture à huile",
    "name_en": "Oil-based paint",
    "unit": "seau",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "produits",
    "stock": 0,
    "catalog_group": "revetements_finitions"
  },
  {
    "id": "PRD-0135",
    "name_fr": "Peinture époxy",
    "name_en": "Epoxy paint",
    "unit": "seau",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "produits",
    "stock": 0,
    "catalog_group": "revetements_finitions"
  },
  {
    "id": "PRD-0136",
    "name_fr": "Peinture anticorrosion",
    "name_en": "Anti-corrosion paint",
    "unit": "seau",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "produits",
    "stock": 0,
    "catalog_group": "revetements_finitions"
  },
  {
    "id": "PRD-0137",
    "name_fr": "Primaires et sous-couches",
    "name_en": "Primers and undercoats",
    "unit": "seau",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "produits",
    "stock": 0,
    "catalog_group": "revetements_finitions"
  },
  {
    "id": "PRD-0138",
    "name_fr": "Diluants et solvants",
    "name_en": "Thinners and solvents",
    "unit": "litre",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "produits",
    "stock": 0,
    "catalog_group": "revetements_finitions"
  },
  {
    "id": "PRD-0139",
    "name_fr": "Rouleaux et pinceaux",
    "name_en": "Rollers and brushes",
    "unit": "lot",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "produits",
    "stock": 0,
    "catalog_group": "revetements_finitions"
  },
  {
    "id": "PRD-0140",
    "name_fr": "Pistolets à peinture",
    "name_en": "Paint spray guns",
    "unit": "unité",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "produits",
    "stock": 0,
    "catalog_group": "revetements_finitions"
  },
  {
    "id": "PRD-0141",
    "name_fr": "Tuyaux PVC",
    "name_en": "PVC pipes",
    "unit": "barre",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "produits",
    "stock": 0,
    "catalog_group": "plomberie_sanitaire"
  },
  {
    "id": "PRD-0142",
    "name_fr": "Tuyaux PPR",
    "name_en": "PPR pipes",
    "unit": "barre",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "produits",
    "stock": 0,
    "catalog_group": "plomberie_sanitaire"
  },
  {
    "id": "PRD-0143",
    "name_fr": "Tuyaux PEHD",
    "name_en": "HDPE pipes",
    "unit": "barre",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "produits",
    "stock": 0,
    "catalog_group": "plomberie_sanitaire"
  },
  {
    "id": "PRD-0144",
    "name_fr": "Tuyaux cuivre",
    "name_en": "Copper pipes",
    "unit": "barre",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "produits",
    "stock": 0,
    "catalog_group": "plomberie_sanitaire"
  },
  {
    "id": "PRD-0145",
    "name_fr": "Tuyaux acier galvanisé",
    "name_en": "Galvanized steel pipes",
    "unit": "barre",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "produits",
    "stock": 0,
    "catalog_group": "plomberie_sanitaire"
  },
  {
    "id": "PRD-0146",
    "name_fr": "Raccords de plomberie",
    "name_en": "Plumbing fittings",
    "unit": "unité",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "produits",
    "stock": 0,
    "catalog_group": "plomberie_sanitaire"
  },
  {
    "id": "PRD-0147",
    "name_fr": "Robinets et vannes",
    "name_en": "Taps and valves",
    "unit": "unité",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "produits",
    "stock": 0,
    "catalog_group": "plomberie_sanitaire"
  },
  {
    "id": "PRD-0148",
    "name_fr": "Pompes de surface",
    "name_en": "Surface pumps",
    "unit": "unité",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "produits",
    "stock": 0,
    "catalog_group": "plomberie_sanitaire"
  },
  {
    "id": "PRD-0149",
    "name_fr": "Pompes immergées",
    "name_en": "Submersible pumps",
    "unit": "unité",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "produits",
    "stock": 0,
    "catalog_group": "plomberie_sanitaire"
  },
  {
    "id": "PRD-0150",
    "name_fr": "Surpresseurs",
    "name_en": "Booster pumps",
    "unit": "unité",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "produits",
    "stock": 0,
    "catalog_group": "plomberie_sanitaire"
  },
  {
    "id": "PRD-0151",
    "name_fr": "Réservoirs d’eau",
    "name_en": "Water tanks",
    "unit": "unité",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "produits",
    "stock": 0,
    "catalog_group": "plomberie_sanitaire"
  },
  {
    "id": "PRD-0152",
    "name_fr": "Chauffe-eau électriques",
    "name_en": "Electric water heaters",
    "unit": "unité",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "produits",
    "stock": 0,
    "catalog_group": "plomberie_sanitaire"
  },
  {
    "id": "PRD-0153",
    "name_fr": "Chauffe-eau solaires",
    "name_en": "Solar water heaters",
    "unit": "unité",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "produits",
    "stock": 0,
    "catalog_group": "plomberie_sanitaire"
  },
  {
    "id": "PRD-0154",
    "name_fr": "WC",
    "name_en": "Toilets",
    "unit": "unité",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "produits",
    "stock": 0,
    "catalog_group": "plomberie_sanitaire"
  },
  {
    "id": "PRD-0155",
    "name_fr": "Lavabos",
    "name_en": "Washbasins",
    "unit": "unité",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "produits",
    "stock": 0,
    "catalog_group": "plomberie_sanitaire"
  },
  {
    "id": "PRD-0156",
    "name_fr": "Urinoirs",
    "name_en": "Urinals",
    "unit": "unité",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "produits",
    "stock": 0,
    "catalog_group": "plomberie_sanitaire"
  },
  {
    "id": "PRD-0157",
    "name_fr": "Éviers",
    "name_en": "Sinks",
    "unit": "unité",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "produits",
    "stock": 0,
    "catalog_group": "plomberie_sanitaire"
  },
  {
    "id": "PRD-0158",
    "name_fr": "Douches et baignoires",
    "name_en": "Showers and bathtubs",
    "unit": "unité",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "produits",
    "stock": 0,
    "catalog_group": "plomberie_sanitaire"
  },
  {
    "id": "PRD-0159",
    "name_fr": "Cabines de douche",
    "name_en": "Shower enclosures",
    "unit": "unité",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "produits",
    "stock": 0,
    "catalog_group": "plomberie_sanitaire"
  },
  {
    "id": "PRD-0160",
    "name_fr": "Mitigeurs et mélangeurs",
    "name_en": "Mixer taps",
    "unit": "unité",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "produits",
    "stock": 0,
    "catalog_group": "plomberie_sanitaire"
  },
  {
    "id": "PRD-0161",
    "name_fr": "Siphons et bondes",
    "name_en": "Traps and wastes",
    "unit": "unité",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "produits",
    "stock": 0,
    "catalog_group": "plomberie_sanitaire"
  },
  {
    "id": "PRD-0162",
    "name_fr": "Fosses septiques",
    "name_en": "Septic tanks",
    "unit": "unité",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "produits",
    "stock": 0,
    "catalog_group": "plomberie_sanitaire"
  },
  {
    "id": "PRD-0163",
    "name_fr": "Biodigesteurs",
    "name_en": "Biodigesters",
    "unit": "unité",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "produits",
    "stock": 0,
    "catalog_group": "plomberie_sanitaire"
  },
  {
    "id": "PRD-0164",
    "name_fr": "Filtres à eau",
    "name_en": "Water filters",
    "unit": "unité",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "produits",
    "stock": 0,
    "catalog_group": "plomberie_sanitaire"
  },
  {
    "id": "PRD-0165",
    "name_fr": "Compteurs d’eau",
    "name_en": "Water meters",
    "unit": "unité",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "produits",
    "stock": 0,
    "catalog_group": "plomberie_sanitaire"
  },
  {
    "id": "PRD-0166",
    "name_fr": "Câbles électriques",
    "name_en": "Electrical cables",
    "unit": "rouleau",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "produits",
    "stock": 0,
    "catalog_group": "electricite_energie"
  },
  {
    "id": "PRD-0167",
    "name_fr": "Fils électriques",
    "name_en": "Electrical wires",
    "unit": "rouleau",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "produits",
    "stock": 0,
    "catalog_group": "electricite_energie"
  },
  {
    "id": "PRD-0168",
    "name_fr": "Gaines et conduits",
    "name_en": "Conduits and trunking",
    "unit": "barre",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "produits",
    "stock": 0,
    "catalog_group": "electricite_energie"
  },
  {
    "id": "PRD-0169",
    "name_fr": "Chemins de câbles",
    "name_en": "Cable trays",
    "unit": "barre",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "produits",
    "stock": 0,
    "catalog_group": "electricite_energie"
  },
  {
    "id": "PRD-0170",
    "name_fr": "Disjoncteurs",
    "name_en": "Circuit breakers",
    "unit": "unité",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "produits",
    "stock": 0,
    "catalog_group": "electricite_energie"
  },
  {
    "id": "PRD-0171",
    "name_fr": "Fusibles et différentiels",
    "name_en": "Fuses and RCDs",
    "unit": "unité",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "produits",
    "stock": 0,
    "catalog_group": "electricite_energie"
  },
  {
    "id": "PRD-0172",
    "name_fr": "Tableaux électriques",
    "name_en": "Electrical panels",
    "unit": "unité",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "produits",
    "stock": 0,
    "catalog_group": "electricite_energie"
  },
  {
    "id": "PRD-0173",
    "name_fr": "Interrupteurs et prises",
    "name_en": "Switches and sockets",
    "unit": "unité",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "produits",
    "stock": 0,
    "catalog_group": "electricite_energie"
  },
  {
    "id": "PRD-0174",
    "name_fr": "Boîtes de dérivation",
    "name_en": "Junction boxes",
    "unit": "unité",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "produits",
    "stock": 0,
    "catalog_group": "electricite_energie"
  },
  {
    "id": "PRD-0175",
    "name_fr": "Ampoules LED",
    "name_en": "LED bulbs",
    "unit": "unité",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "produits",
    "stock": 0,
    "catalog_group": "electricite_energie"
  },
  {
    "id": "PRD-0176",
    "name_fr": "Luminaires",
    "name_en": "Light fixtures",
    "unit": "unité",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "produits",
    "stock": 0,
    "catalog_group": "electricite_energie"
  },
  {
    "id": "PRD-0177",
    "name_fr": "Projecteurs LED",
    "name_en": "LED floodlights",
    "unit": "unité",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "produits",
    "stock": 0,
    "catalog_group": "electricite_energie"
  },
  {
    "id": "PRD-0178",
    "name_fr": "Mâts et poteaux",
    "name_en": "Lighting poles",
    "unit": "unité",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "produits",
    "stock": 0,
    "catalog_group": "electricite_energie"
  },
  {
    "id": "PRD-0179",
    "name_fr": "Compteurs électriques",
    "name_en": "Electricity meters",
    "unit": "unité",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "produits",
    "stock": 0,
    "catalog_group": "electricite_energie"
  },
  {
    "id": "PRD-0180",
    "name_fr": "Parafoudres",
    "name_en": "Surge protectors",
    "unit": "unité",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "produits",
    "stock": 0,
    "catalog_group": "electricite_energie"
  },
  {
    "id": "PRD-0181",
    "name_fr": "Piquets de terre",
    "name_en": "Earth rods",
    "unit": "unité",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "produits",
    "stock": 0,
    "catalog_group": "electricite_energie"
  },
  {
    "id": "PRD-0182",
    "name_fr": "Groupes électrogènes",
    "name_en": "Generators",
    "unit": "unité",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "produits",
    "stock": 0,
    "catalog_group": "electricite_energie"
  },
  {
    "id": "PRD-0183",
    "name_fr": "Onduleurs et stabilisateurs",
    "name_en": "UPS and stabilizers",
    "unit": "unité",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "produits",
    "stock": 0,
    "catalog_group": "electricite_energie"
  },
  {
    "id": "PRD-0184",
    "name_fr": "Panneaux solaires",
    "name_en": "Solar panels",
    "unit": "unité",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "produits",
    "stock": 0,
    "catalog_group": "electricite_energie"
  },
  {
    "id": "PRD-0185",
    "name_fr": "Batteries solaires",
    "name_en": "Solar batteries",
    "unit": "unité",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "produits",
    "stock": 0,
    "catalog_group": "electricite_energie"
  },
  {
    "id": "PRD-0186",
    "name_fr": "Convertisseurs",
    "name_en": "Inverters",
    "unit": "unité",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "produits",
    "stock": 0,
    "catalog_group": "electricite_energie"
  },
  {
    "id": "PRD-0187",
    "name_fr": "Régulateurs solaires",
    "name_en": "Solar charge controllers",
    "unit": "unité",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "produits",
    "stock": 0,
    "catalog_group": "electricite_energie"
  },
  {
    "id": "PRD-0188",
    "name_fr": "Bornes de recharge",
    "name_en": "Charging stations",
    "unit": "unité",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "produits",
    "stock": 0,
    "catalog_group": "electricite_energie"
  },
  {
    "id": "PRD-0189",
    "name_fr": "Détecteurs de mouvement",
    "name_en": "Motion detectors",
    "unit": "unité",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "produits",
    "stock": 0,
    "catalog_group": "electricite_energie"
  },
  {
    "id": "PRD-0190",
    "name_fr": "Interphones et vidéophones",
    "name_en": "Intercoms and video intercoms",
    "unit": "unité",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "produits",
    "stock": 0,
    "catalog_group": "electricite_energie"
  },
  {
    "id": "PRD-0191",
    "name_fr": "Équipements domotiques",
    "name_en": "Home automation equipment",
    "unit": "kit",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "produits",
    "stock": 0,
    "catalog_group": "electricite_energie"
  },
  {
    "id": "PRD-0192",
    "name_fr": "Caméras CCTV",
    "name_en": "CCTV cameras",
    "unit": "unité",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "produits",
    "stock": 0,
    "catalog_group": "securite"
  },
  {
    "id": "PRD-0193",
    "name_fr": "Enregistreurs vidéo",
    "name_en": "Video recorders",
    "unit": "unité",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "produits",
    "stock": 0,
    "catalog_group": "securite"
  },
  {
    "id": "PRD-0194",
    "name_fr": "Alarmes anti-intrusion",
    "name_en": "Intrusion alarms",
    "unit": "kit",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "produits",
    "stock": 0,
    "catalog_group": "securite"
  },
  {
    "id": "PRD-0195",
    "name_fr": "Détecteurs de fumée",
    "name_en": "Smoke detectors",
    "unit": "unité",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "produits",
    "stock": 0,
    "catalog_group": "securite"
  },
  {
    "id": "PRD-0196",
    "name_fr": "Détecteurs de gaz",
    "name_en": "Gas detectors",
    "unit": "unité",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "produits",
    "stock": 0,
    "catalog_group": "securite"
  },
  {
    "id": "PRD-0197",
    "name_fr": "Extincteurs",
    "name_en": "Fire extinguishers",
    "unit": "unité",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "produits",
    "stock": 0,
    "catalog_group": "securite"
  },
  {
    "id": "PRD-0198",
    "name_fr": "RIA",
    "name_en": "Fire hose reels",
    "unit": "unité",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "produits",
    "stock": 0,
    "catalog_group": "securite"
  },
  {
    "id": "PRD-0199",
    "name_fr": "Portes coupe-feu",
    "name_en": "Fire doors",
    "unit": "unité",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "produits",
    "stock": 0,
    "catalog_group": "securite"
  },
  {
    "id": "PRD-0200",
    "name_fr": "Signalisation de sécurité",
    "name_en": "Safety signs",
    "unit": "unité",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "produits",
    "stock": 0,
    "catalog_group": "securite"
  },
  {
    "id": "PRD-0201",
    "name_fr": "Coffres-forts",
    "name_en": "Safes",
    "unit": "unité",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "produits",
    "stock": 0,
    "catalog_group": "securite"
  },
  {
    "id": "PRD-0202",
    "name_fr": "Contrôle d’accès biométrique",
    "name_en": "Biometric access control",
    "unit": "kit",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "produits",
    "stock": 0,
    "catalog_group": "securite"
  },
  {
    "id": "PRD-0203",
    "name_fr": "Clôtures électriques",
    "name_en": "Electric fences",
    "unit": "mètre",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "produits",
    "stock": 0,
    "catalog_group": "securite"
  },
  {
    "id": "PRD-0204",
    "name_fr": "Casques de chantier",
    "name_en": "Safety helmets",
    "unit": "unité",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "produits",
    "stock": 0,
    "catalog_group": "securite"
  },
  {
    "id": "PRD-0205",
    "name_fr": "Chaussures de sécurité",
    "name_en": "Safety boots",
    "unit": "paire",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "produits",
    "stock": 0,
    "catalog_group": "securite"
  },
  {
    "id": "PRD-0206",
    "name_fr": "Gants de protection",
    "name_en": "Safety gloves",
    "unit": "paire",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "produits",
    "stock": 0,
    "catalog_group": "securite"
  },
  {
    "id": "PRD-0207",
    "name_fr": "Lunettes de protection",
    "name_en": "Safety goggles",
    "unit": "unité",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "produits",
    "stock": 0,
    "catalog_group": "securite"
  },
  {
    "id": "PRD-0208",
    "name_fr": "Harnais de sécurité",
    "name_en": "Safety harnesses",
    "unit": "unité",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "produits",
    "stock": 0,
    "catalog_group": "securite"
  },
  {
    "id": "PRD-0209",
    "name_fr": "Gilets réfléchissants",
    "name_en": "Reflective vests",
    "unit": "unité",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "produits",
    "stock": 0,
    "catalog_group": "securite"
  },
  {
    "id": "PRD-0210",
    "name_fr": "Masques respiratoires",
    "name_en": "Respiratory masks",
    "unit": "unité",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "produits",
    "stock": 0,
    "catalog_group": "securite"
  },
  {
    "id": "PRD-0211",
    "name_fr": "Trousses de premiers secours",
    "name_en": "First aid kits",
    "unit": "unité",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "produits",
    "stock": 0,
    "catalog_group": "securite"
  },
  {
    "id": "PRD-0212",
    "name_fr": "Géotextiles",
    "name_en": "Geotextiles",
    "unit": "rouleau",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "produits",
    "stock": 0,
    "catalog_group": "routes_assainissement"
  },
  {
    "id": "PRD-0213",
    "name_fr": "Géomembranes",
    "name_en": "Geomembranes",
    "unit": "rouleau",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "produits",
    "stock": 0,
    "catalog_group": "routes_assainissement"
  },
  {
    "id": "PRD-0214",
    "name_fr": "Buses et dalots",
    "name_en": "Culverts",
    "unit": "unité",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "produits",
    "stock": 0,
    "catalog_group": "routes_assainissement"
  },
  {
    "id": "PRD-0215",
    "name_fr": "Caniveaux et grilles",
    "name_en": "Drains and grates",
    "unit": "unité",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "produits",
    "stock": 0,
    "catalog_group": "routes_assainissement"
  },
  {
    "id": "PRD-0216",
    "name_fr": "Regards",
    "name_en": "Manholes",
    "unit": "unité",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "produits",
    "stock": 0,
    "catalog_group": "routes_assainissement"
  },
  {
    "id": "PRD-0217",
    "name_fr": "Bitume et émulsion",
    "name_en": "Bitumen and emulsion",
    "unit": "tonne",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "produits",
    "stock": 0,
    "catalog_group": "routes_assainissement"
  },
  {
    "id": "PRD-0218",
    "name_fr": "Signalisation routière",
    "name_en": "Road signs",
    "unit": "unité",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "produits",
    "stock": 0,
    "catalog_group": "routes_assainissement"
  },
  {
    "id": "PRD-0219",
    "name_fr": "Glissières de sécurité",
    "name_en": "Road safety barriers",
    "unit": "mètre",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "produits",
    "stock": 0,
    "catalog_group": "routes_assainissement"
  },
  {
    "id": "PRD-0220",
    "name_fr": "Produits de stabilisation des sols",
    "name_en": "Soil stabilization products",
    "unit": "sac",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "produits",
    "stock": 0,
    "catalog_group": "routes_assainissement"
  },
  {
    "id": "PRD-0221",
    "name_fr": "Pompes d’exhaure",
    "name_en": "Dewatering pumps",
    "unit": "unité",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "produits",
    "stock": 0,
    "catalog_group": "routes_assainissement"
  },
  {
    "id": "PRD-0222",
    "name_fr": "Tuyaux de drainage",
    "name_en": "Drainage pipes",
    "unit": "barre",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "produits",
    "stock": 0,
    "catalog_group": "routes_assainissement"
  },
  {
    "id": "PRD-0223",
    "name_fr": "Bacs à graisse",
    "name_en": "Grease traps",
    "unit": "unité",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "produits",
    "stock": 0,
    "catalog_group": "routes_assainissement"
  },
  {
    "id": "PRD-0224",
    "name_fr": "Poubelles et bennes",
    "name_en": "Bins and skips",
    "unit": "unité",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "produits",
    "stock": 0,
    "catalog_group": "routes_assainissement"
  },
  {
    "id": "PRD-0225",
    "name_fr": "Truelles et taloches",
    "name_en": "Trowels and floats",
    "unit": "unité",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "produits",
    "stock": 0,
    "catalog_group": "outillage_engins"
  },
  {
    "id": "PRD-0226",
    "name_fr": "Niveaux et mètres",
    "name_en": "Levels and measuring tapes",
    "unit": "unité",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "produits",
    "stock": 0,
    "catalog_group": "outillage_engins"
  },
  {
    "id": "PRD-0227",
    "name_fr": "Marteaux et burins",
    "name_en": "Hammers and chisels",
    "unit": "unité",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "produits",
    "stock": 0,
    "catalog_group": "outillage_engins"
  },
  {
    "id": "PRD-0228",
    "name_fr": "Pinces et clés",
    "name_en": "Pliers and spanners",
    "unit": "unité",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "produits",
    "stock": 0,
    "catalog_group": "outillage_engins"
  },
  {
    "id": "PRD-0229",
    "name_fr": "Scies",
    "name_en": "Saws",
    "unit": "unité",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "produits",
    "stock": 0,
    "catalog_group": "outillage_engins"
  },
  {
    "id": "PRD-0230",
    "name_fr": "Perceuses et perforateurs",
    "name_en": "Drills and rotary hammers",
    "unit": "unité",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "produits",
    "stock": 0,
    "catalog_group": "outillage_engins"
  },
  {
    "id": "PRD-0231",
    "name_fr": "Meuleuses",
    "name_en": "Angle grinders",
    "unit": "unité",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "produits",
    "stock": 0,
    "catalog_group": "outillage_engins"
  },
  {
    "id": "PRD-0232",
    "name_fr": "Bétonnières",
    "name_en": "Concrete mixers",
    "unit": "unité",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "produits",
    "stock": 0,
    "catalog_group": "outillage_engins"
  },
  {
    "id": "PRD-0233",
    "name_fr": "Vibrateurs à béton",
    "name_en": "Concrete vibrators",
    "unit": "unité",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "produits",
    "stock": 0,
    "catalog_group": "outillage_engins"
  },
  {
    "id": "PRD-0234",
    "name_fr": "Plaques vibrantes",
    "name_en": "Plate compactors",
    "unit": "unité",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "produits",
    "stock": 0,
    "catalog_group": "outillage_engins"
  },
  {
    "id": "PRD-0235",
    "name_fr": "Postes à souder",
    "name_en": "Welding machines",
    "unit": "unité",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "produits",
    "stock": 0,
    "catalog_group": "outillage_engins"
  },
  {
    "id": "PRD-0236",
    "name_fr": "Compresseurs",
    "name_en": "Compressors",
    "unit": "unité",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "produits",
    "stock": 0,
    "catalog_group": "outillage_engins"
  },
  {
    "id": "PRD-0237",
    "name_fr": "Échelles",
    "name_en": "Ladders",
    "unit": "unité",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "produits",
    "stock": 0,
    "catalog_group": "outillage_engins"
  },
  {
    "id": "PRD-0238",
    "name_fr": "Échafaudages",
    "name_en": "Scaffolding",
    "unit": "lot",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "produits",
    "stock": 0,
    "catalog_group": "outillage_engins"
  },
  {
    "id": "PRD-0239",
    "name_fr": "Brouettes",
    "name_en": "Wheelbarrows",
    "unit": "unité",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "produits",
    "stock": 0,
    "catalog_group": "outillage_engins"
  },
  {
    "id": "PRD-0240",
    "name_fr": "Pelles, pioches et râteaux",
    "name_en": "Shovels, picks and rakes",
    "unit": "unité",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "produits",
    "stock": 0,
    "catalog_group": "outillage_engins"
  },
  {
    "id": "PRD-0241",
    "name_fr": "Matériel topographique",
    "name_en": "Surveying equipment",
    "unit": "kit",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "produits",
    "stock": 0,
    "catalog_group": "outillage_engins"
  },
  {
    "id": "PRD-0242",
    "name_fr": "Laser de chantier",
    "name_en": "Construction laser",
    "unit": "unité",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "produits",
    "stock": 0,
    "catalog_group": "outillage_engins"
  },
  {
    "id": "PRD-0243",
    "name_fr": "Pelles hydrauliques",
    "name_en": "Excavators",
    "unit": "unité",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "produits",
    "stock": 0,
    "catalog_group": "outillage_engins"
  },
  {
    "id": "PRD-0244",
    "name_fr": "Bulldozers",
    "name_en": "Bulldozers",
    "unit": "unité",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "produits",
    "stock": 0,
    "catalog_group": "outillage_engins"
  },
  {
    "id": "PRD-0245",
    "name_fr": "Chargeuses",
    "name_en": "Loaders",
    "unit": "unité",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "produits",
    "stock": 0,
    "catalog_group": "outillage_engins"
  },
  {
    "id": "PRD-0246",
    "name_fr": "Niveleuses",
    "name_en": "Graders",
    "unit": "unité",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "produits",
    "stock": 0,
    "catalog_group": "outillage_engins"
  },
  {
    "id": "PRD-0247",
    "name_fr": "Compacteurs",
    "name_en": "Road rollers",
    "unit": "unité",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "produits",
    "stock": 0,
    "catalog_group": "outillage_engins"
  },
  {
    "id": "PRD-0248",
    "name_fr": "Grues",
    "name_en": "Cranes",
    "unit": "unité",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "produits",
    "stock": 0,
    "catalog_group": "outillage_engins"
  },
  {
    "id": "PRD-0249",
    "name_fr": "Chariots élévateurs",
    "name_en": "Forklifts",
    "unit": "unité",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "produits",
    "stock": 0,
    "catalog_group": "outillage_engins"
  },
  {
    "id": "PRD-0250",
    "name_fr": "Nacelles",
    "name_en": "Aerial work platforms",
    "unit": "unité",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "produits",
    "stock": 0,
    "catalog_group": "outillage_engins"
  },
  {
    "id": "PRD-0251",
    "name_fr": "Camions-bennes",
    "name_en": "Dump trucks",
    "unit": "unité",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "produits",
    "stock": 0,
    "catalog_group": "outillage_engins"
  },
  {
    "id": "PRD-0252",
    "name_fr": "Camions-grues",
    "name_en": "Truck cranes",
    "unit": "unité",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "produits",
    "stock": 0,
    "catalog_group": "outillage_engins"
  },
  {
    "id": "PRD-0253",
    "name_fr": "Camions-citernes",
    "name_en": "Tanker trucks",
    "unit": "unité",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "produits",
    "stock": 0,
    "catalog_group": "outillage_engins"
  },
  {
    "id": "PRD-0254",
    "name_fr": "Pompes à béton",
    "name_en": "Concrete pumps",
    "unit": "unité",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "produits",
    "stock": 0,
    "catalog_group": "outillage_engins"
  },
  {
    "id": "PRD-0255",
    "name_fr": "Tractopelles",
    "name_en": "Backhoe loaders",
    "unit": "unité",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "produits",
    "stock": 0,
    "catalog_group": "outillage_engins"
  },
  {
    "id": "PRD-0256",
    "name_fr": "Foreuses",
    "name_en": "Drilling rigs",
    "unit": "unité",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "produits",
    "stock": 0,
    "catalog_group": "outillage_engins"
  },
  {
    "id": "PRD-0257",
    "name_fr": "Concasseurs et cribles",
    "name_en": "Crushers and screens",
    "unit": "unité",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "produits",
    "stock": 0,
    "catalog_group": "outillage_engins"
  },
  {
    "id": "SVC-0001",
    "name_fr": "Visite technique",
    "name_en": "Technical site visit",
    "unit": "service",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "services",
    "stock": 0,
    "catalog_group": "etudes"
  },
  {
    "id": "SVC-0002",
    "name_fr": "Étude de faisabilité",
    "name_en": "Feasibility study",
    "unit": "service",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "services",
    "stock": 0,
    "catalog_group": "etudes"
  },
  {
    "id": "SVC-0003",
    "name_fr": "Conception architecturale",
    "name_en": "Architectural design",
    "unit": "service",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "services",
    "stock": 0,
    "catalog_group": "etudes"
  },
  {
    "id": "SVC-0004",
    "name_fr": "Plans 2D et visualisation 3D",
    "name_en": "2D plans and 3D visualization",
    "unit": "service",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "services",
    "stock": 0,
    "catalog_group": "etudes"
  },
  {
    "id": "SVC-0005",
    "name_fr": "Étude géotechnique",
    "name_en": "Geotechnical study",
    "unit": "service",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "services",
    "stock": 0,
    "catalog_group": "etudes"
  },
  {
    "id": "SVC-0006",
    "name_fr": "Levé topographique",
    "name_en": "Topographic survey",
    "unit": "service",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "services",
    "stock": 0,
    "catalog_group": "etudes"
  },
  {
    "id": "SVC-0007",
    "name_fr": "Métré et estimation",
    "name_en": "Quantity survey and estimate",
    "unit": "service",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "services",
    "stock": 0,
    "catalog_group": "etudes"
  },
  {
    "id": "SVC-0008",
    "name_fr": "Devis et proforma",
    "name_en": "Quotation and proforma",
    "unit": "service",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "services",
    "stock": 0,
    "catalog_group": "etudes"
  },
  {
    "id": "SVC-0009",
    "name_fr": "Planification de chantier",
    "name_en": "Construction planning",
    "unit": "service",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "services",
    "stock": 0,
    "catalog_group": "etudes"
  },
  {
    "id": "SVC-0010",
    "name_fr": "Assistance au permis de construire",
    "name_en": "Building permit assistance",
    "unit": "service",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "services",
    "stock": 0,
    "catalog_group": "etudes"
  },
  {
    "id": "SVC-0011",
    "name_fr": "Sélection de prestataires",
    "name_en": "Contractor selection",
    "unit": "service",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "services",
    "stock": 0,
    "catalog_group": "etudes"
  },
  {
    "id": "SVC-0012",
    "name_fr": "Conseil en matériaux",
    "name_en": "Materials consulting",
    "unit": "service",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "services",
    "stock": 0,
    "catalog_group": "etudes"
  },
  {
    "id": "SVC-0013",
    "name_fr": "Construction clé en main",
    "name_en": "Turnkey construction",
    "unit": "service",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "services",
    "stock": 0,
    "catalog_group": "travaux"
  },
  {
    "id": "SVC-0014",
    "name_fr": "Construction par lots",
    "name_en": "Construction by trade packages",
    "unit": "service",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "services",
    "stock": 0,
    "catalog_group": "travaux"
  },
  {
    "id": "SVC-0015",
    "name_fr": "Fondations et terrassement",
    "name_en": "Foundations and earthworks",
    "unit": "service",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "services",
    "stock": 0,
    "catalog_group": "travaux"
  },
  {
    "id": "SVC-0016",
    "name_fr": "Maçonnerie et béton",
    "name_en": "Masonry and concrete works",
    "unit": "service",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "services",
    "stock": 0,
    "catalog_group": "travaux"
  },
  {
    "id": "SVC-0017",
    "name_fr": "Coffrage et ferraillage",
    "name_en": "Formwork and reinforcement",
    "unit": "service",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "services",
    "stock": 0,
    "catalog_group": "travaux"
  },
  {
    "id": "SVC-0018",
    "name_fr": "Charpente et toiture",
    "name_en": "Roof framing and roofing",
    "unit": "service",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "services",
    "stock": 0,
    "catalog_group": "travaux"
  },
  {
    "id": "SVC-0019",
    "name_fr": "Installation électrique",
    "name_en": "Electrical installation",
    "unit": "service",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "services",
    "stock": 0,
    "catalog_group": "travaux"
  },
  {
    "id": "SVC-0020",
    "name_fr": "Plomberie et sanitaire",
    "name_en": "Plumbing and sanitary installation",
    "unit": "service",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "services",
    "stock": 0,
    "catalog_group": "travaux"
  },
  {
    "id": "SVC-0021",
    "name_fr": "Climatisation et ventilation",
    "name_en": "Air conditioning and ventilation",
    "unit": "service",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "services",
    "stock": 0,
    "catalog_group": "travaux"
  },
  {
    "id": "SVC-0022",
    "name_fr": "Menuiserie bois",
    "name_en": "Wood carpentry",
    "unit": "service",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "services",
    "stock": 0,
    "catalog_group": "travaux"
  },
  {
    "id": "SVC-0023",
    "name_fr": "Menuiserie aluminium",
    "name_en": "Aluminium joinery",
    "unit": "service",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "services",
    "stock": 0,
    "catalog_group": "travaux"
  },
  {
    "id": "SVC-0024",
    "name_fr": "Soudure et ferronnerie",
    "name_en": "Welding and metalwork",
    "unit": "service",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "services",
    "stock": 0,
    "catalog_group": "travaux"
  },
  {
    "id": "SVC-0025",
    "name_fr": "Carrelage et revêtements",
    "name_en": "Tiling and floor coverings",
    "unit": "service",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "services",
    "stock": 0,
    "catalog_group": "travaux"
  },
  {
    "id": "SVC-0026",
    "name_fr": "Peinture et décoration",
    "name_en": "Painting and decoration",
    "unit": "service",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "services",
    "stock": 0,
    "catalog_group": "travaux"
  },
  {
    "id": "SVC-0027",
    "name_fr": "Étanchéité",
    "name_en": "Waterproofing",
    "unit": "service",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "services",
    "stock": 0,
    "catalog_group": "travaux"
  },
  {
    "id": "SVC-0028",
    "name_fr": "Faux plafonds et plâtrerie",
    "name_en": "Ceilings and plastering",
    "unit": "service",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "services",
    "stock": 0,
    "catalog_group": "travaux"
  },
  {
    "id": "SVC-0029",
    "name_fr": "Aménagement intérieur",
    "name_en": "Interior fit-out",
    "unit": "service",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "services",
    "stock": 0,
    "catalog_group": "travaux"
  },
  {
    "id": "SVC-0030",
    "name_fr": "Aménagement extérieur",
    "name_en": "Exterior landscaping",
    "unit": "service",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "services",
    "stock": 0,
    "catalog_group": "travaux"
  },
  {
    "id": "SVC-0031",
    "name_fr": "Installation solaire",
    "name_en": "Solar installation",
    "unit": "service",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "services",
    "stock": 0,
    "catalog_group": "travaux"
  },
  {
    "id": "SVC-0032",
    "name_fr": "Domotique et contrôle d’accès",
    "name_en": "Home automation and access control",
    "unit": "service",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "services",
    "stock": 0,
    "catalog_group": "travaux"
  },
  {
    "id": "SVC-0033",
    "name_fr": "CCTV et alarmes",
    "name_en": "CCTV and alarm installation",
    "unit": "service",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "services",
    "stock": 0,
    "catalog_group": "travaux"
  },
  {
    "id": "SVC-0034",
    "name_fr": "Protection incendie",
    "name_en": "Fire protection installation",
    "unit": "service",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "services",
    "stock": 0,
    "catalog_group": "travaux"
  },
  {
    "id": "SVC-0035",
    "name_fr": "Construction routière",
    "name_en": "Road construction",
    "unit": "service",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "services",
    "stock": 0,
    "catalog_group": "travaux"
  },
  {
    "id": "SVC-0036",
    "name_fr": "Pavage et bordures",
    "name_en": "Paving and curbs",
    "unit": "service",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "services",
    "stock": 0,
    "catalog_group": "travaux"
  },
  {
    "id": "SVC-0037",
    "name_fr": "Drainage et assainissement",
    "name_en": "Drainage and sanitation",
    "unit": "service",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "services",
    "stock": 0,
    "catalog_group": "travaux"
  },
  {
    "id": "SVC-0038",
    "name_fr": "Forage et puits",
    "name_en": "Drilling and wells",
    "unit": "service",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "services",
    "stock": 0,
    "catalog_group": "travaux"
  },
  {
    "id": "SVC-0039",
    "name_fr": "Installation de pompes",
    "name_en": "Pump installation",
    "unit": "service",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "services",
    "stock": 0,
    "catalog_group": "travaux"
  },
  {
    "id": "SVC-0040",
    "name_fr": "Exhaure de chantier",
    "name_en": "Construction dewatering",
    "unit": "service",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "services",
    "stock": 0,
    "catalog_group": "travaux"
  },
  {
    "id": "SVC-0041",
    "name_fr": "Supervision de chantier",
    "name_en": "Construction supervision",
    "unit": "service",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "services",
    "stock": 0,
    "catalog_group": "logistique"
  },
  {
    "id": "SVC-0042",
    "name_fr": "Contrôle qualité",
    "name_en": "Quality control",
    "unit": "service",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "services",
    "stock": 0,
    "catalog_group": "logistique"
  },
  {
    "id": "SVC-0043",
    "name_fr": "Coordination des sous-traitants",
    "name_en": "Subcontractor coordination",
    "unit": "service",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "services",
    "stock": 0,
    "catalog_group": "logistique"
  },
  {
    "id": "SVC-0044",
    "name_fr": "Gestion HSE",
    "name_en": "HSE management",
    "unit": "service",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "services",
    "stock": 0,
    "catalog_group": "logistique"
  },
  {
    "id": "SVC-0045",
    "name_fr": "Approvisionnement chantier",
    "name_en": "Site procurement",
    "unit": "service",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "services",
    "stock": 0,
    "catalog_group": "logistique"
  },
  {
    "id": "SVC-0046",
    "name_fr": "Location d’engins avec opérateur",
    "name_en": "Equipment rental with operator",
    "unit": "service",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "services",
    "stock": 0,
    "catalog_group": "logistique"
  },
  {
    "id": "SVC-0047",
    "name_fr": "Location d’outillage",
    "name_en": "Tool rental",
    "unit": "service",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "services",
    "stock": 0,
    "catalog_group": "logistique"
  },
  {
    "id": "SVC-0048",
    "name_fr": "Livraison avec suivi GPS",
    "name_en": "GPS-tracked delivery",
    "unit": "service",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "services",
    "stock": 0,
    "catalog_group": "logistique"
  },
  {
    "id": "SVC-0049",
    "name_fr": "Transport de matériaux",
    "name_en": "Materials transport",
    "unit": "service",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "services",
    "stock": 0,
    "catalog_group": "logistique"
  },
  {
    "id": "SVC-0050",
    "name_fr": "Évacuation des déblais",
    "name_en": "Debris removal",
    "unit": "service",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "services",
    "stock": 0,
    "catalog_group": "logistique"
  },
  {
    "id": "SVC-0051",
    "name_fr": "Gardiennage de chantier",
    "name_en": "Site security",
    "unit": "service",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "services",
    "stock": 0,
    "catalog_group": "logistique"
  },
  {
    "id": "SVC-0052",
    "name_fr": "Nettoyage de fin de chantier",
    "name_en": "Post-construction cleaning",
    "unit": "service",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "services",
    "stock": 0,
    "catalog_group": "maintenance"
  },
  {
    "id": "SVC-0053",
    "name_fr": "Réception technique",
    "name_en": "Technical handover",
    "unit": "service",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "services",
    "stock": 0,
    "catalog_group": "maintenance"
  },
  {
    "id": "SVC-0054",
    "name_fr": "Rapport de conformité",
    "name_en": "Compliance report",
    "unit": "service",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "services",
    "stock": 0,
    "catalog_group": "maintenance"
  },
  {
    "id": "SVC-0055",
    "name_fr": "Correction des malfaçons",
    "name_en": "Defect correction",
    "unit": "service",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "services",
    "stock": 0,
    "catalog_group": "maintenance"
  },
  {
    "id": "SVC-0056",
    "name_fr": "Maintenance préventive",
    "name_en": "Preventive maintenance",
    "unit": "service",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "services",
    "stock": 0,
    "catalog_group": "maintenance"
  },
  {
    "id": "SVC-0057",
    "name_fr": "Dépannage urgent",
    "name_en": "Emergency repair",
    "unit": "service",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "services",
    "stock": 0,
    "catalog_group": "maintenance"
  },
  {
    "id": "SVC-0058",
    "name_fr": "Rénovation de bâtiment",
    "name_en": "Building renovation",
    "unit": "service",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "services",
    "stock": 0,
    "catalog_group": "maintenance"
  },
  {
    "id": "SVC-0059",
    "name_fr": "Gestion immobilière",
    "name_en": "Property management",
    "unit": "service",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "services",
    "stock": 0,
    "catalog_group": "maintenance"
  },
  {
    "id": "SVC-0060",
    "name_fr": "Entretien électrique",
    "name_en": "Electrical maintenance",
    "unit": "service",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "services",
    "stock": 0,
    "catalog_group": "maintenance"
  },
  {
    "id": "SVC-0061",
    "name_fr": "Entretien plomberie",
    "name_en": "Plumbing maintenance",
    "unit": "service",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "services",
    "stock": 0,
    "catalog_group": "maintenance"
  },
  {
    "id": "SVC-0062",
    "name_fr": "Entretien toiture",
    "name_en": "Roof maintenance",
    "unit": "service",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "services",
    "stock": 0,
    "catalog_group": "maintenance"
  },
  {
    "id": "SVC-0063",
    "name_fr": "Entretien climatisation",
    "name_en": "HVAC maintenance",
    "unit": "service",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "services",
    "stock": 0,
    "catalog_group": "maintenance"
  },
  {
    "id": "SVC-0064",
    "name_fr": "Entretien espaces verts",
    "name_en": "Grounds maintenance",
    "unit": "service",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "services",
    "stock": 0,
    "catalog_group": "maintenance"
  },
  {
    "id": "SVC-0065",
    "name_fr": "Désinfection et lutte antiparasitaire",
    "name_en": "Disinfection and pest control",
    "unit": "service",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "services",
    "stock": 0,
    "catalog_group": "numerique"
  },
  {
    "id": "SVC-0066",
    "name_fr": "Calculateur de quantités",
    "name_en": "Quantity calculator",
    "unit": "service",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "services",
    "stock": 0,
    "catalog_group": "numerique"
  },
  {
    "id": "SVC-0067",
    "name_fr": "Comparaison des prix",
    "name_en": "Price comparison",
    "unit": "service",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "services",
    "stock": 0,
    "catalog_group": "numerique"
  },
  {
    "id": "SVC-0068",
    "name_fr": "Demande de devis multiple",
    "name_en": "Multiple quote request",
    "unit": "service",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "services",
    "stock": 0,
    "catalog_group": "numerique"
  },
  {
    "id": "SVC-0069",
    "name_fr": "Simulation du coût du projet",
    "name_en": "Project cost simulation",
    "unit": "service",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "services",
    "stock": 0,
    "catalog_group": "numerique"
  },
  {
    "id": "SVC-0070",
    "name_fr": "Suivi photo de chantier",
    "name_en": "Photo site monitoring",
    "unit": "service",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "services",
    "stock": 0,
    "catalog_group": "numerique"
  },
  {
    "id": "SVC-0071",
    "name_fr": "Assistance technique à distance",
    "name_en": "Remote technical support",
    "unit": "service",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "services",
    "stock": 0,
    "catalog_group": "numerique"
  },
  {
    "id": "SVC-0072",
    "name_fr": "Réservation d’artisan",
    "name_en": "Tradesperson booking",
    "unit": "service",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "services",
    "stock": 0,
    "catalog_group": "numerique"
  },
  {
    "id": "SVC-0073",
    "name_fr": "Vérification des artisans",
    "name_en": "Tradesperson verification",
    "unit": "service",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "services",
    "stock": 0,
    "catalog_group": "metiers"
  },
  {
    "id": "SVC-0074",
    "name_fr": "Architecture",
    "name_en": "Architecture",
    "unit": "service",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "services",
    "stock": 0,
    "catalog_group": "metiers"
  },
  {
    "id": "SVC-0075",
    "name_fr": "Ingénierie civile",
    "name_en": "Civil engineering",
    "unit": "service",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "services",
    "stock": 0,
    "catalog_group": "metiers"
  },
  {
    "id": "SVC-0076",
    "name_fr": "Géomètre-topographe",
    "name_en": "Land surveying",
    "unit": "service",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "services",
    "stock": 0,
    "catalog_group": "metiers"
  },
  {
    "id": "SVC-0077",
    "name_fr": "Maçonnerie",
    "name_en": "Masonry",
    "unit": "service",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "services",
    "stock": 0,
    "catalog_group": "metiers"
  },
  {
    "id": "SVC-0078",
    "name_fr": "Coffrage",
    "name_en": "Formwork",
    "unit": "service",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "services",
    "stock": 0,
    "catalog_group": "metiers"
  },
  {
    "id": "SVC-0079",
    "name_fr": "Ferraillage",
    "name_en": "Steel fixing",
    "unit": "service",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "services",
    "stock": 0,
    "catalog_group": "metiers"
  },
  {
    "id": "SVC-0080",
    "name_fr": "Plomberie",
    "name_en": "Plumbing",
    "unit": "service",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "services",
    "stock": 0,
    "catalog_group": "metiers"
  },
  {
    "id": "SVC-0081",
    "name_fr": "Électricité bâtiment",
    "name_en": "Building electrical work",
    "unit": "service",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "services",
    "stock": 0,
    "catalog_group": "metiers"
  },
  {
    "id": "SVC-0082",
    "name_fr": "Électricité industrielle",
    "name_en": "Industrial electrical work",
    "unit": "service",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "services",
    "stock": 0,
    "catalog_group": "metiers"
  },
  {
    "id": "SVC-0083",
    "name_fr": "Carrelage",
    "name_en": "Tiling",
    "unit": "service",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "services",
    "stock": 0,
    "catalog_group": "metiers"
  },
  {
    "id": "SVC-0084",
    "name_fr": "Peinture",
    "name_en": "Painting",
    "unit": "service",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "services",
    "stock": 0,
    "catalog_group": "metiers"
  },
  {
    "id": "SVC-0085",
    "name_fr": "Plâtrerie",
    "name_en": "Plastering",
    "unit": "service",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "services",
    "stock": 0,
    "catalog_group": "metiers"
  },
  {
    "id": "SVC-0086",
    "name_fr": "Menuiserie",
    "name_en": "Carpentry",
    "unit": "service",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "services",
    "stock": 0,
    "catalog_group": "metiers"
  },
  {
    "id": "SVC-0087",
    "name_fr": "Vitrerie",
    "name_en": "Glazing",
    "unit": "service",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "services",
    "stock": 0,
    "catalog_group": "metiers"
  },
  {
    "id": "SVC-0088",
    "name_fr": "Serrurerie",
    "name_en": "Locksmithing",
    "unit": "service",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "services",
    "stock": 0,
    "catalog_group": "metiers"
  },
  {
    "id": "SVC-0089",
    "name_fr": "Chaudronnerie",
    "name_en": "Boilermaking",
    "unit": "service",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "services",
    "stock": 0,
    "catalog_group": "metiers"
  },
  {
    "id": "SVC-0090",
    "name_fr": "Tuyauterie",
    "name_en": "Pipefitting",
    "unit": "service",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "services",
    "stock": 0,
    "catalog_group": "metiers"
  },
  {
    "id": "SVC-0091",
    "name_fr": "Froid et climatisation",
    "name_en": "Refrigeration and air conditioning",
    "unit": "service",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "services",
    "stock": 0,
    "catalog_group": "metiers"
  },
  {
    "id": "SVC-0092",
    "name_fr": "Jardinage et paysagisme",
    "name_en": "Gardening and landscaping",
    "unit": "service",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "services",
    "stock": 0,
    "catalog_group": "metiers"
  },
  {
    "id": "SVC-0093",
    "name_fr": "Mécanique d’engins",
    "name_en": "Heavy equipment mechanics",
    "unit": "service",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "services",
    "stock": 0,
    "catalog_group": "metiers"
  },
  {
    "id": "SVC-0094",
    "name_fr": "Électromécanique",
    "name_en": "Electromechanics",
    "unit": "service",
    "price": 0,
    "img": "assets/mesproduits.png",
    "category": "services",
    "stock": 0,
    "catalog_group": "metiers"
  }
];

module.exports = { CONSTRUCTION_CATALOG };
